

# this is .travis.yml 
# comments also gives us something to edit and thus contrive
# a reason to `git push` and trigger a build to see if it's working

language: php

php: 
  - 5.6
  - 7.0

install:  composer install

# there may be a better way, but to compel travis-ci to use our test 
# config (sqlite) we replace the configuration file.
# and create a data/log directory

before_script:  
    - cp config/autoload/doctrine.test.php config/autoload/doctrine.local.php
    - mkdir -p data/log 

script: vendor/bin/phpunit

