

# this is .travis.yml 
# comments also gives us something to edit and thus contrive
# a reason to `git push` and trigger a build to see if it's working

language: php

php: 
  - 5.6
  - 7.0

install:  composer install

before_script:  cp module/Application/test/config/autoload/doctrine.test.php config/autoload/doctrine.local.php

script: vendor/bin/phpunit

