

# this is .travis.yml
# comments also gives us something to edit and thus contrive
# a reason to `git push` and trigger a build to see if it's working

language: php

php:
# we broke 5.6 compatibility, so disable this at least for the time being
# - 5.6
  - 7.0
  - 7.1

install:  composer install

services:
    - mysql
    
# there may be a better way, but to compel travis-ci to use our test
# config (sqlite) we replace the configuration file.

before_script:
    - cp config/autoload/doctrine.test.php config/autoload/doctrine.local.php
    #- cp config/autoload/forms.test.php config/autoload/forms.local.php
    - mkdir -p data/log
    - mkdir data/cache
    - phpenv config-rm xdebug.ini

script: vendor/bin/phpunit

# thank you, https://gist.github.com/Pierstoval/5d3101055e9d6a5fc19e
cache:
  directories:
    - $HOME/.composer/cache
